name: Deploy to Remote Server

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Deploy via SSH
        run: |
          ssh username@your-remote-server 'docker stop neorilla || true && docker rm neorilla || true'
          docker save neorilla | ssh username@your-remote-server 'docker load'
          ssh username@your-remote-server 'docker run -d -p 4000:80 --name neorilla neorilla'

